#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd#!/bin/bash
grep -V "bin" /etc/passwd
